# SPDX-License-Identifier:  MPL-2.0
PREFIX bhv: <https://secorolab.github.io/metamodels/behaviour#>
PREFIX bdd: <https://secorolab.github.io/metamodels/acceptance-criteria/bdd#>
PREFIX obs: <https://secorolab.github.io/metamodels/observation#>

CONSTRUCT {
    ?scenarioExec a ?execType ;
        bdd:of-variant ?scenarioVar ;
        bdd:of-template ?scenarioTmpl ;
        bdd:has-behaviour-implementation ?bhvImpl ;
        obs:has-policy ?obsPolicy .
    ?bhvImpl a ?bhvImplType ;
        bhv:of-behaviour ?behaviour .
    ?obsPolicy a ?obsPolicyType ;
        bdd:of-clause ?fluentClause .
    ?behaviour a ?bhvType .
}
WHERE {
    ?scenarioExec a bdd:ScenarioExecution ;
        a ?execType ;
        bdd:of-variant ?scenarioVar ;
        bdd:has-behaviour-implementation ?bhvImpl ;
        obs:has-policy ?obsPolicy .

    ?scenarioVar a bdd:ScenarioVariant ;
        bdd:of-template ?scenarioTmpl .

    ?scenarioTmpl a bdd:ScenarioTemplate ;
        bdd:of-scenario / bhv:of-behaviour ?behaviour .

    ?bhvImpl
        a bdd:BehaviourImplementation ;
        a ?bhvImplType ;
        bhv:of-behaviour ?behaviour .

    ?obsPolicy
        a obs:ObservationPolicy ;
        a ?obsPolicyType ;
        bdd:of-clause ?fluentClause .

    ?behaviour
        a bhv:Behaviour ;
        a ?bhvType .
}
